global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:9114']

  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:9103']
